FROM python:3.6

RUN pip install --upgrade pip==20.2.4

COPY web/scripts/fpdiff.sh /usr/bin

RUN pip3 install \
    "flake8<3.6" \
    "pycodestyle<2.4"

WORKDIR /code

ENTRYPOINT ["/bin/bash", "/usr/bin/fpdiff.sh"]

