version: '3'
services:
  mysql:
    container_name: mc-mysql
    image: mysql:5.7.21
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql_entrypoint:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mc_dev
