FROM python:3.7-slim-buster
RUN apt update
RUN apt install -y git
RUN pip install python-semantic-release==5.2.0 
RUN git config --global user.email semantic-release@masschallenge.org
RUN mkdir /app
WORKDIR /app
ADD setup.cfg .

