# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-11 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'managed': True, 'ordering': ['startup'], 'verbose_name_plural': 'Applications'},
        ),
        migrations.AlterModelOptions(
            name='applicationanswer',
            options={'managed': True, 'verbose_name_plural': 'Application Answers'},
        ),
        migrations.AlterModelOptions(
            name='applicationpanelassignment',
            options={'managed': True, 'ordering': ['panel_slot_number'], 'verbose_name_plural': 'assignments of startup applications to panel'},
        ),
        migrations.AlterModelOptions(
            name='applicationquestion',
            options={'managed': True, 'ordering': ['application_type', 'question_number'], 'verbose_name_plural': 'Application Questions'},
        ),
        migrations.AlterModelOptions(
            name='applicationtype',
            options={'managed': True, 'verbose_name_plural': 'Application Types'},
        ),
        migrations.AlterModelOptions(
            name='baseprofile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bucketstate',
            options={'managed': True, 'ordering': ['sort_order']},
        ),
        migrations.AlterModelOptions(
            name='clearance',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='entrepreneurprofile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='expertcategory',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Expert Category', 'verbose_name_plural': 'Expert Categories'},
        ),
        migrations.AlterModelOptions(
            name='expertinterest',
            options={'managed': True, 'verbose_name_plural': 'Expert Interests'},
        ),
        migrations.AlterModelOptions(
            name='expertinteresttype',
            options={'managed': True, 'verbose_name_plural': 'Expert Interest Types'},
        ),
        migrations.AlterModelOptions(
            name='expertprofile',
            options={'managed': True, 'permissions': (('change_password', 'Can change users passwords directly'),)},
        ),
        migrations.AlterModelOptions(
            name='functionalexpertise',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'managed': True, 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='interestcategory',
            options={'managed': True, 'verbose_name_plural': 'Interest Categories'},
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'managed': True, 'verbose_name_plural': 'Job postings for startups'},
        ),
        migrations.AlterModelOptions(
            name='judgeapplicationfeedback',
            options={'managed': True, 'verbose_name_plural': 'Judge Application Feedback'},
        ),
        migrations.AlterModelOptions(
            name='judgeavailability',
            options={'managed': True, 'ordering': ['panel_time__start_date_time', 'panel_type__panel_type', 'panel_location__location'], 'verbose_name_plural': 'Judge availability for specific Panel types, times, locations'},
        ),
        migrations.AlterModelOptions(
            name='judgefeedbackcomponent',
            options={'managed': True, 'verbose_name_plural': 'Feedback Components'},
        ),
        migrations.AlterModelOptions(
            name='judgepanelassignment',
            options={'managed': True, 'verbose_name_plural': 'assignments of judge to panel'},
        ),
        migrations.AlterModelOptions(
            name='judgeroundcommitment',
            options={'managed': True, 'verbose_name_plural': 'Judge commitment to participate in a Judging Round'},
        ),
        migrations.AlterModelOptions(
            name='judgingform',
            options={'managed': True, 'verbose_name_plural': 'Judging Forms'},
        ),
        migrations.AlterModelOptions(
            name='judgingformelement',
            options={'managed': True, 'ordering': ['form_type', 'element_number'], 'verbose_name_plural': 'Judging Form Elements'},
        ),
        migrations.AlterModelOptions(
            name='judginground',
            options={'managed': True, 'ordering': ['program__program_status', '-program__end_date', '-end_date_time', 'name'], 'verbose_name_plural': 'Judging Rounds'},
        ),
        migrations.AlterModelOptions(
            name='memberprofile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='mentoringspecialties',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Mentoring Specialty', 'verbose_name_plural': 'Mentoring Specialties'},
        ),
        migrations.AlterModelOptions(
            name='mentorprogramofficehour',
            options={'managed': True, 'ordering': ['date', 'start_time'], 'verbose_name': 'Office Hour'},
        ),
        migrations.AlterModelOptions(
            name='namedgroup',
            options={'managed': True, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'managed': True, 'ordering': ('-created_at', 'name')},
        ),
        migrations.AlterModelOptions(
            name='newsletterreceipt',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='observer',
            options={'managed': True, 'ordering': ['last_name', 'first_name'], 'verbose_name': 'Observer', 'verbose_name_plural': 'Observers'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'managed': True, 'ordering': ['name'], 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='panel',
            options={'managed': True, 'verbose_name_plural': 'Panels'},
        ),
        migrations.AlterModelOptions(
            name='panellocation',
            options={'managed': True, 'verbose_name_plural': 'Panel Locations'},
        ),
        migrations.AlterModelOptions(
            name='paneltime',
            options={'managed': True, 'verbose_name_plural': 'Panel Times'},
        ),
        migrations.AlterModelOptions(
            name='paneltype',
            options={'managed': True, 'verbose_name_plural': 'Panel Types'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'managed': True, 'ordering': ['organization__name'], 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='partnerteammember',
            options={'managed': True, 'ordering': ['team_member__first_name'], 'verbose_name_plural': 'Partner Team Members'},
        ),
        migrations.AlterModelOptions(
            name='paypalpayment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='paypalrefund',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'managed': True, 'ordering': ['-end_date', 'name'], 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterModelOptions(
            name='programadministrator',
            options={'managed': True, 'verbose_name_plural': 'Program Administrator'},
        ),
        migrations.AlterModelOptions(
            name='programadministratorpermission',
            options={'managed': True, 'verbose_name_plural': 'Program Administrator Permissions'},
        ),
        migrations.AlterModelOptions(
            name='programcycle',
            options={'managed': True, 'verbose_name_plural': 'program cycles'},
        ),
        migrations.AlterModelOptions(
            name='programfamily',
            options={'managed': True, 'verbose_name_plural': 'program families'},
        ),
        migrations.AlterModelOptions(
            name='programoverride',
            options={'managed': True, 'verbose_name_plural': 'Program Overrides'},
        ),
        migrations.AlterModelOptions(
            name='programpartner',
            options={'managed': True, 'ordering': ['program__name', 'partner_type__sort_order', 'partner'], 'verbose_name_plural': 'Program Partner'},
        ),
        migrations.AlterModelOptions(
            name='programpartnertype',
            options={'managed': True, 'ordering': ['program', 'sort_order'], 'verbose_name_plural': 'Program Partner Types'},
        ),
        migrations.AlterModelOptions(
            name='programrole',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Program Role', 'verbose_name_plural': 'Program Roles'},
        ),
        migrations.AlterModelOptions(
            name='programrolegrant',
            options={'managed': True, 'verbose_name': 'Program Role Grant', 'verbose_name_plural': 'Program Role Grants'},
        ),
        migrations.AlterModelOptions(
            name='programstartupattribute',
            options={'managed': True, 'ordering': ['program', 'attribute_label']},
        ),
        migrations.AlterModelOptions(
            name='programstartupstatus',
            options={'managed': True, 'ordering': ['program', 'sort_order', 'startup_status'], 'verbose_name_plural': 'Program Startup Statuses'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='recommendationtag',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='refundcode',
            options={'managed': True, 'verbose_name_plural': 'Refund Codes'},
        ),
        migrations.AlterModelOptions(
            name='refundcoderedemption',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scenario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scenarioapplication',
            options={'managed': True, 'verbose_name_plural': 'Scenario Applications'},
        ),
        migrations.AlterModelOptions(
            name='scenariojudge',
            options={'managed': True, 'verbose_name_plural': 'Scenario Judges'},
        ),
        migrations.AlterModelOptions(
            name='scenariopreference',
            options={'managed': True, 'ordering': ['priority']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'managed': True, 'ordering': ('newsletter', 'sequence')},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='siteprogramauthorization',
            options={'managed': True, 'verbose_name_plural': 'Site Program Authorizations'},
        ),
        migrations.AlterModelOptions(
            name='startup',
            options={'managed': True, 'ordering': ['organization__name'], 'verbose_name_plural': 'Startups'},
        ),
        migrations.AlterModelOptions(
            name='startupattribute',
            options={'managed': True, 'verbose_name_plural': 'Startup Attributes'},
        ),
        migrations.AlterModelOptions(
            name='startupcycleinterest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='startuplabel',
            options={'managed': True, 'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='startupmentorrelationship',
            options={'managed': True, 'verbose_name_plural': 'Startup Mentor Relationships'},
        ),
        migrations.AlterModelOptions(
            name='startupmentortrackingrecord',
            options={'managed': True, 'verbose_name': 'Mentor Tracking Record', 'verbose_name_plural': 'Mentor Tracking Records'},
        ),
        migrations.AlterModelOptions(
            name='startupoverridegrant',
            options={'managed': True, 'verbose_name_plural': 'Startup Override Grants'},
        ),
        migrations.AlterModelOptions(
            name='startupprograminterest',
            options={'managed': True, 'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='startuprole',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='startupstatus',
            options={'managed': True, 'verbose_name_plural': 'Startup Statuses'},
        ),
        migrations.AlterModelOptions(
            name='startupteammember',
            options={'managed': True, 'verbose_name_plural': 'Startup Team Members'},
        ),
        migrations.AlterModelOptions(
            name='userlabel',
            options={'managed': True, 'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'managed': True},
        ),
    ]
