# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-30 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impact', '0002_set_models_to_managed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprograminterest',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
